Global:
  use_gpu: True
  epoch_num: 100
  log_smooth_window: 20
  print_batch_step: 10
  save_model_dir: "./output/det_model/"
  save_epoch_step: 10
  eval_batch_step: [0, 500]
  pretrained_model: ""  # Kosongkan untuk pretrain dari awal
  save_inference_dir: "./output/det_model/"
  use_visualdl: False
  save_res_path: "./output/det_results.txt"

Architecture:
  model_type: det
  algorithm: DB
  Backbone:
    name: MobileNetV3
    scale: 0.5
    model_name: "large"
    disable_se: True
  Neck:
    name: RSEFPN
    out_channels: 96
  Head:
    name: DBHead
    k: 50

Loss:
  name: DBLoss
  alpha: 5
  beta: 10
  ohem_ratio: 3

Optimizer:
  name: Adam
  beta1: 0.9
  beta2: 0.999
  clip_norm: 5
  lr:
    name: Cosine
    learning_rate: 0.001

PostProcess:
  name: DBPostProcess
  box_thresh: 0.5
  unclip_ratio: 1.5

Metric:
  name: DetMetric
  main_indicator: hmean

Train:
  dataset:
    name: SimpleDataSet
    data_dir: "dataset/images/"
    label_file_list: ["dataset/train_list.txt"]
    ratio_list: [1.0]
    transforms:
      - DecodeImage: { img_mode: "BGR", channel_first: false }
      - DetLabelEncode:
      - IaaAugment: { augmenter_args: [ { type: Fliplr, args: { p: 0.5 } } ] }
      - EastRandomCropData: { size: [640, 640], max_tries: 50, keep_ratio: true }
      - Resize: { size: [640, 640] }
      - KeepKeys: { keep_keys: ['image', 'polys']}
  loader:
    shuffle: true
    batch_size_per_card: 8
    drop_last: false
    num_workers: 4

Eval:
  dataset:
    name: SimpleDataSet
    data_dir: "dataset/images/"
    label_file_list: ["dataset/train_list.txt"]
    transforms:
      - DecodeImage: { img_mode: "BGR", channel_first: false }
      - DetLabelEncode:
      - Resize: { size: [640, 640] }
      - KeepKeys: { keep_keys: ["image", "polys", "ignore_tags"] }
  loader:
    shuffle: false
    drop_last: false
    batch_size_per_card: 1
    num_workers: 4

Transform: 
  name: TPS  # Bisa diganti dengan None jika tidak digunakan
  num_fiducial: 20
  img_size: [32, 100]
  input_channel: 1
  output_channel: 512