Global:
  use_gpu: True
  epoch_num: 150
  log_smooth_window: 20
  character_dict_path: dataset/dict.txt
  save_model_dir: ./output/rec_jawa2
  print_batch_step: 10
  save_epoch_step: 5
  eval_batch_step: [0, 2000]
  cal_metric_during_train: True
  pretrained_model: null
  checkpoints: null
  save_inference_dir: null
  use_visualdl: False
  infer_img: doc/imgs_words_en/word_10.png
  use_space_char: True
  distributed: False
  save_res_path: ./output/rec_jawa2/predicts.txt

Architecture:
  model_type: rec
  algorithm: CRNN
  Transform:
  Backbone:
    name: MobileNetV1Enhance
    scale: 0.5
  Neck:
    name: SequenceEncoder
    encoder_type: rnn
    hidden_size: 96
  Head:
    name: CTCHead
    fc_decay: 0.001

Loss:
  name: CTCLoss

Optimizer:
  name: Adam
  beta1: 0.9
  beta2: 0.999
  lr:
    learning_rate: 0.01
  regularizer:
    name: L2
    factor: 0.001

PostProcess:
  name: CTCLabelDecode

Metric:
  name: RecMetric
  main_indicator: acc

Train:
  dataset:
    name: SimpleDataSet
    data_dir: dataset/
    label_file_list: ["dataset/train.txt"]
    transforms:
      - DecodeImage: {img_mode: "RGB", channel_first: False}
      - RecResizeImg: {image_shape: [3, 32, 320]}
      - CTCLabelEncode:
          max_text_length: 25
      - KeepKeys: {keep_keys: ["image", "label", "length"]}
  loader:
    shuffle: True
    batch_size_per_card: 28
    drop_last: True
    num_workers: 0
    use_shared_memory: False

Eval:
  dataset:
    name: SimpleDataSet
    data_dir: dataset/
    label_file_list: ["dataset/test.txt"]
    transforms:
      - DecodeImage: {img_mode: "RGB", channel_first: False}
      - RecResizeImg: {image_shape: [3, 32, 320]}
      - CTCLabelEncode:
          max_text_length: 25
      - KeepKeys: {keep_keys: ["image", "label", "length"]}
  loader:
    shuffle: False
    drop_last: False
    batch_size_per_card: 16
    num_workers: 0
    use_shared_memory: False