Global:
  debug: false
  use_gpu: True
  epoch_num: 1100
  log_smooth_window: 20
  character_dict_path: dataset/dict.txt
  save_model_dir: ./output/rec_jawa6
  print_batch_step: 10
  save_epoch_step: 20
  eval_batch_step: [0, 2000]
  cal_metric_during_train: True
  pretrained_model: null
  checkpoints: null
  save_inference_dir: null
  use_visualdl: False
  infer_img: doc/imgs_words_en/word_10.png
  use_space_char: True
  distributed: True
  infer_mode: false
  save_res_path: ./output/rec_jawa6/predicts.txt
  max_text_length: &max_text_length 25
  

Optimizer:
  name: Adam
  beta1: 0.9
  beta2: 0.999
  lr:
    name: Cosine
    learning_rate: 0.001
    warmup_epoch: 5
  regularizer:
    name: L2
    factor: 3.0e-05


Architecture:
  model_type: rec
  algorithm: SVTR_LCNet
  Transform:
  Backbone:
    name: MobileNetV1Enhance
    scale: 0.5
    last_conv_stride: [1, 2]
    last_pool_type: avg
    last_pool_kernel_size: [2, 2]
  Head:
    name: MultiHead
    head_list:
      - CTCHead:
          Neck:
            name: svtr
            dims: 64
            depth: 2
            hidden_dims: 120
            use_guide: True
          Head:
            fc_decay: 0.00001
      - SARHead:
          enc_dim: 512
          max_text_length: *max_text_length

Loss:
  name: MultiLoss
  loss_config_list:
    - CTCLoss:
    - SARLoss:

PostProcess:  
  name: CTCLabelDecode

Metric:
  name: RecMetric
  main_indicator: acc
  ignore_space: False

Train:
  dataset:
    name: SimpleDataSet
    ext_op_transform_idx: 1
    data_dir: dataset/
    label_file_list: ["dataset/train.txt"]
    transforms:
    - DecodeImage:
        img_mode: BGR
        channel_first: false
    - RecConAug:
        prob: 0.5
        ext_data_num: 2
        image_shape: [48, 320, 3]
        max_text_length: *max_text_length
    - RecAug:
    - MultiLabelEncode:
    - RecResizeImg:
        image_shape: [3, 48, 320]
    - KeepKeys:
        keep_keys:
        - image
        - label_ctc
        - label_sar
        - length
        - valid_ratio
  loader:
    shuffle: true
    batch_size_per_card: 16
    drop_last: true
    num_workers: 4

Eval:
  dataset:
    name: SimpleDataSet
    data_dir: dataset/
    label_file_list: ["dataset/test.txt"]
    transforms:
      - DecodeImage: {img_mode: "BGR", channel_first: False}
      - RecResizeImg: {image_shape: [3, 48, 320]}
      - CTCLabelEncode:
          max_text_length: 25
      - KeepKeys: {keep_keys: ["image", "label", "length"]}
  loader:
    shuffle: False
    drop_last: False
    batch_size_per_card: 16
    num_workers: 4
    use_shared_memory: False