Global:
  use_gpu: False
  cal_metric_during_train: False
  character_dict_path: dataset/dict.txt
  pretrained_model: output/rec_jawa/latest
  save_res_path: output/rec_jawa/predicts.txt
  infer_img: ./train_data/rec/test/img_81.jpg  # opsional
  use_space_char: True

Architecture:
  model_type: rec
  algorithm: CRNN
  Backbone:
    name: MobileNetV1Enhance
    scale: 0.5
    last_conv_stride: [1, 2]
    last_pool_type: avg
  Neck:
    name: SequenceEncoder
    encoder_type: rnn
    hidden_size: 96
  Head:
    name: CTCHead
    fc_decay: 0.00001

PostProcess:
  name: CTCLabelDecode

Metric:
  name: RecMetric
  main_indicator: acc

Eval:
  dataset:
    name: SimpleDataSet
    data_dir: dataset/
    label_file_list: ["dataset/test.txt"]
    transforms:
      - DecodeImage: {img_mode: "RGB", channel_first: False}
      - RecResizeImg: {image_shape: [3, 32, 320]}
      - CTCLabelEncode:
          max_text_length: 25
      - KeepKeys: {keep_keys: ["image", "label", "length"]}
  loader:
    shuffle: False
    drop_last: False
    batch_size_per_card: 16
    num_workers: 0
    use_shared_memory: False